# Site settings
title: Nostalgic Memories
email: nostalgicmemorieshd@google.com
url: https://nostalgicmemorieshd.com
description: "Minimal, Nostalgia based Youtube Videos"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Nostalgic Memories

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://www.facebook.com/nostalgicmemorieshd/
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
  - title: Instagram
    url: https://www.instagram.com/nostalgicmemorieshd/
  - title: Youtube
    url: https://www.youtube.com/nostalgicmemorieshd

# Build settings
markdown: kramdown
permalink: pretty
